version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jimiva5550
      - MONGO_INITDB_ROOT_PASSWORD=jimiva5550
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
